configs/components/pdk-runtime.rb, configs/components/rubygem-nokogiri.rb, configs/projects/pdk.rb
=> Adds some security updates

configs/components/pdk-runtime.rb, configs/components/pdk-templates.json, configs/components/pdk-templates.rb, configs/components/rubygem-bundler.rb, configs/projects/pdk.rb
There will be a followup PR to revert the second commit in this PR after pdk-runtime packages have updated.
Integration testing results:
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/job/platform_pdk_pdk-int-sys-testing_master/79/
=> (PDK-784) Add config for additional_rubies (only 2.1.9 right now) [phase 1/2]

configs/components/pdk-runtime.rb, configs/components/pdk-templates.rb, configs/components/rubygem-bundler.rb
Integration testing results:
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/job/platform_pdk_pdk-int-sys-testing_master/86/
=> (PDK-784) Reintroduce Ruby 2.1.9 into packages [part 2/2]

configs/components/puppet-forge-api.rb
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/job/platform_pdk_pdk-van-build_master/160/
=> (MAINT) Bump to latest puppet gems and be platform specific on Windows

configs/components/pdk-runtime.rb, configs/projects/pdk.rb
Phase 2 of switching the pdk/pdk-runtime settings inheritance.
This build is currently in progress: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/job/platform_pdk_pdk-van-build_master/238/
=> (PDK-915) Migrate shared settings to pdk-runtime config

resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1
Reverts puppetlabs/pdk-vanagon#184
Have to revert this change due to seeing the following errors in Windows.
Env: Windows 10 Ent x64 - Powershell v5.1
https://gist.github.com/bmjen/da44a1c5af75eaf9dbefc4068467a742
=> Revert "(PDK-632) Ensure clean environment on Windows"

configs/components/pdk-templates.rb, configs/platforms/fedora-30-x86_64.rb, configs/projects/pdk.rb
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/35/
=> (PDK-1397) Add Fedora 30 to vanagon config

configs/components/pdk-templates.rb, configs/platforms/debian-10-amd64.rb, configs/projects/pdk.rb
Waiting on build to go through the adhoc pipeline
=> (PDK-1440) Add Debian 10 to vanagon config

configs/components/rubygem-minitar.rb, configs/projects/pdk.rb, resources/files/posix/pdk_env_wrapper, resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-van-build_adhoc/82/
=> (maint) Bump runtime to 201910020

configs/components/pdk-templates.rb
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/89/
=> (PDK-1610) Temporarily pin litmus to 0.14.0

configs/components/pdk-templates.rb
The previous issues with unf_ext (PDK-1610) have been resolved.
=> (MAINT) Un-pin Litmus

Gemfile, configs/platforms/osx-10.15-x86_64.rb
=> (PDK-1522) Add OSX 10.15 to platform configs

resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1
Stand back, I'm doing ~~SCIENCE~~ POWERSHELL!
=> (PDK-1589) Do not use ANSICon when running over WinRM

configs/components/puppet-forge-api.rb
cc @sanfrancrisko 
This is something we should work on automating somehow as well.
=> (MAINT) Bump vendored puppet versions

configs/projects/pdk.rb
Blocked by https://github.com/puppetlabs/vanagon/pull/652
=> (RE-13303) Update project definition to sign PuppetDevelopmentKit.psm1 at build time

configs/components/pdk-templates.rb
This reverts commit 29208e5af65b09b44acd7f479cf947a055e4e369.
=> Revert "Only install system_tests gem on the main ruby"

README.md, resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psd1
Removal of any offensive or inappropriate terminology from the code base.
Related PR: https://github.com/puppetlabs/ci-job-configs/pull/7690
=> (IAC-1446) - Removal of Inappropriate Terminology

Gemfile, configs/platforms/debian-11-amd64.rb, configs/platforms/fedora-32-x86_64.rb, configs/platforms/fedora-34-x86_64.rb, configs/platforms/osx-11-x86_64.rb, configs/platforms/windows-2012r2-x64.rb
Reverts puppetlabs/pdk-vanagon#288
=> Revert "(puppetlabs/pdk#1093) Add new platform support for pdk; Bump vanagon ver"

configs/components/rubygem-pdk.json
=> (PDK-1764) 2.4.0 release prep

configs/platforms/osx-12-x86_64.rb
=> (CONT-507) Add OSX 12 platform

configs/platforms/el-9-x86_64.rb
Adding RHEL 9 platform file to add RHEL 9 support for pdk
=> (CONT-550) Add RHEL9 platform file

configs/projects/pdk.rb, resources/windows/wix/localization/puppet_en-us.wxl
The url was incorrectly pointing to 1.x this commit updates it so that we point to latest.
=> (MAINT) Update docs url for references

configs/components/pdk-templates.json
Provide a detailed description of all the changes present in this pull request.
=> (maint) Manually bump templates version

configs/components/rubygem-pdk.json
Bumping the SHA and Version of the PDK
=> (CAT-1612) PDK v3.0.1

configs/platforms/debian-11-aarch64.rb
https://github.com/puppetlabs/pdk/issues/1162
=> (maint) add Debian 11 aarch64 platform

Gemfile, configs/platforms/debian-12-aarch64.rb, configs/platforms/debian-12-amd64.rb
Successful build
https://jenkins-platform.delivery.puppetlabs.net/job/platform_pdk_pdk-van-init_main/709/
=> (CAT-1790) add debian 12 support

configs/components/pdk-templates.json
Provide a detailed description of all the changes present in this pull request.
=> Promote pdk-templates

configs/components/pdk-runtime.rb
Leave the augeas lense in place within the pdk-runtime
=> (CAT-646) Cancel the removal of the augeas lense

configs/components/pdk-templates.json
Auto-pin job seems to be broken
=> (maint) Pin pdk-templates to 1e9f9cf7ebbf5609667cf79dd06a9af194a26f8c

configs/platforms/ubuntu-24.04-aarch64.rb, configs/platforms/ubuntu-24.04-amd64.rb
Provide a detailed description of all the changes present in this pull request.
=> (CAT-1995) - Add Ubuntu 24.04

configs/components/pdk-templates.json
Known issues with auto update job
=> (maint) Pin pdk-templates to 5d17ec13eb4ee24ae7d768707988e77e61d9fb24

configs/components/pdk-templates.json
=> (maint) Promote pdk-template to d3cc13f9ce535e0be246014dea76f58a9d0dfc41

configs/components/pdk-templates.json
=> Promote pdk-templates to e63947089a0633ee75f75825070c35f2ff4035cd

configs/components/pdk-templates.json
=> Promote pdk-templates to 7e53a025a94217bd636583431dd60f5f0c7371e2

configs/components/pdk-templates.json
=> Promote pdk-templates to d5f5ac14ec9a540fd1ff4f44f5418e3545405aa2

configs/components/pdk-templates.json
=> Promote pdk-templates to 8fb22fc1950747cc6a49efa87d64b809d691d02a

configs/components/rubygem-pdk.json
=> Promote pdk to 88a831294073ed082e801aadcefe23e46a57dae8
