Gemfile
configs/projects/pdk.rb
ext/build_defaults.yaml

This updates the PDK project to point to a 'PDK' repo
on the download servers.
Also updates to Packaging 1.0.x branch for updated shipping automation.

Autoshipping to PDK repos

---

Gemfile
configs/projects/pdk.rb
ext/build_defaults.yaml

Reverts puppetlabs/pdk-vanagon#95, as it is assumed to be breaking the build:
```
bundler: failed to load command: repo (/tmp/jenkins/workspace/platform_pdk_pkg-van-repo_master/.bundle/gems/ruby/2.3.0/bin/repo)
RuntimeError: createrepo tool not found...exiting
/tmp/jenkins/workspace/platform_pdk_pkg-van-repo_master/.bundle/gems/ruby/2.3.0/bundler/gems/packaging-84c019ede3f1/lib/packaging/util/tool.rb:28:in `find_tool'
/tmp/jenkins/workspace/platform_pdk_pkg-van-repo_master/.bundle/gems/ruby/2.3.0/bundler/gems/packaging-84c019ede3f1/lib/packaging/util/tool.rb:9:in `check_tool'
/tmp/jenkins/workspace/platform_pdk_pkg-van-repo_master/.bundle/gems/ruby/2.3.0/bundler/gems/packaging-84c019ede3f1/lib/packaging/rpm/repo.rb:26:in `repo_creation_command' …
```

Revert "Autoshipping to PDK repos"

---

Gemfile
configs/projects/pdk.rb
ext/build_defaults.yaml

Reverts puppetlabs/pdk-vanagon#96
We found and fixed an issue in the packaging 1.0.x update with repo creation. Let's try again!

Revert "Revert "Autoshipping to PDK repos""

---

ext/build_defaults.yaml

This commit sets the `nonfinal_repo_name` to 'puppet5-nightly' so that nightly builds land in the correct repos.

(maint) Add nonfinal_repo_name

---

configs/components/pdk-templates.rb
configs/components/puppet-forge-api.rb
configs/components/task-schema.rb
configs/projects/pdk.rb

I got the bundler invocation figured out to prevent it from installing duplicates copies of puppet+deps into the generic gem cache, but it's commented out right now to prevent breaking the builds (or forcing PDK to install puppet at runtime). Once PDK knows where to look for the puppet gems we can re-enable that (https://github.com/puppetlabs/pdk-vanagon/pull/121/files#diff-0fa2fe03c607920e7b6b10aaf45f0c56R66) and reduce the package size a bit.

(PDK-787) Cache various puppet gems and their dependencies

---

configs/components/puppet-forge-api.rb

Dropping (for now at least) the idea of resolving what puppets to cache at build-time. I think it introduces too much complexity (and non-reproducibility) to the build process.
But this does bring the pe_versions.json file from the forge-api codebase into the cachedir at build time.
With this approach we would just PR changes to the `puppet_rubyapi_versions` mapping data structure in this file when we want to add a new puppet gem to the cache. We could move that mapping to a JSON file down the road to make auto-promotion easier.

(PDK-828) Cache pe_versions.json from puppet-forge-api codebase

---

configs/components/rubygem-cri.rb

This update is to support https://github.com/puppetlabs/pdk/pull/466

(maint) Update cri to 2.10.1

---

configs/components/pdk-templates.rb
configs/components/puppet-forge-api.rb

Haven't been able to test this fully yet due to vmpooler running out of windows images.

(FIXUP) Avoid replacing the bundle.bat wrappers on windows

---

configs/components/pdk-runtime.rb
configs/platforms/osx-10.13-x86_64.rb

Provisioning is a little intense because we actually need an up to date homebrew which refuses to run as root now, but this seems to work.
Tested a built package and was able to create a module, validate & test on multiple puppet/ruby versions, convert a module (puppetlabs-motd), and validate, test, and build that converted module.

(PDK-399) Add macOS 10.13 (High Sierra) platform config

---

configs/components/puppet-forge-api.rb
resources/files/windows/ruby_gem_wrapper.bat

Rewrites paths in the rubygems generated batch files so that `C:\ProgramFiles64Folder\PuppetLabs\` becomes `C:\Program Files\Puppet Labs\`

(PDK-969) rewrite gem .bat wrappers for additional rubies

---

Gemfile

This commit adds a Z version to the packaging gem dependency. Previously, older
versions could get pulled in, which don't have necessary updates, like new
platforms, which causes shipping to fail.

(maint) Be more specific with packaging dependency

---

configs/components/pdk-templates.rb
configs/platforms/fedora-26-x86_64.rb
configs/platforms/fedora-27-x86_64.rb

This commit updates the fedora platform configs to not use the 'f' prefix in
versions and, instead, use 'fc<version>' as the dist tag, which is standard for
fedora packages.

(CPR-391) Fedora packages have odd distro tag

---

configs/components/puppet-forge-api.rb

This PR will add the beaker dependencies that require native compilation to the pdk gem cache. The gems have been natively built and uploaded to artifactory. The JSON gem is only needed on Ruby 2.4.0, since the vendored JSON 1.8.1 with Ruby 2.1.9 should satisfy the version requirement from beaker-aws. The extra logic for the byebug gem is because I had to build a fat gem that included the built extensions for each respective version of Ruby, and also add logic to the build script to put the correct extension into the right directory.

(PDK-950) Adds some pre-compiled beaker depends

---

configs/components/pdk-templates.rb

puppet-strings has been added to the meta gems, so they will be included in the PDK cache due to that.

(maint) Removes puppet-strings from experimental gems list.

---

configs/components/pdk-templates.rb
configs/components/puppet-forge-api.rb
configs/projects/pdk.rb

Adds Puppet 6 and Ruby 2.5.1 to the PDK cache. Also adds Nokogiri to the cache for more than just Windows and for all ruby versions, since we can't assume that modules that use beaker are going to be defaulted to Ruby 2.4.4.

(PDK-1056, PDK-1141) Adds Ruby 2.5.1 and Puppet 6.0.0 to PDK packaging

---

configs/components/puppet-forge-api.rb

The batch files need to be updated in both the shared cache and in the private ruby bins.

(maint) Update batch file shims on Windows for all rubies.

---

ext/build_defaults.yaml

This commit updates the `repo_name` and `nonfinal_repo_name` params to
`puppet6` and `puppet6-nightly`, respectively. These params are used by the
packaging repo to determine where to ship packages. This is especially
necessary for shipping nightly builds to the most-current repo.

(maint) Update `repo_name` and `nonfinal_repo_name` for puppet6

---

configs/components/pdk-templates.rb
configs/platforms/osx-10.13-x86_64.rb

Fixes up steps 1-3 of the packaging pipeline. Depends on puppetlabs/pdk#595 being merged first, then c0c2ada can be dropped from this PR.

(maint) Clear up packaging pipeline errors

---

resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

Clear out any existing environment variables that might affect the PDK Ruby environment on Windows before executing. This matches the behaviour of the POSIX wrapper.

(PDK-632) Ensure clean environment on Windows

---

resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

Previously users could run PDK within the Windows PowerShell ISE application and
it would hang while waiting for user input.  This is a known issue with the ISE
dating back to 2009 [1].  This commit adds a guard on the PowerShell Host called
'Windows PowerShell ISE Host' and throws a helpful error message to the user and
terminates early, not running PDK and not hanging.
[1] https://devblogs.microsoft.com/powershell/console-application-non-support-in-the-ise/

(PDK-1168) Add guard in PS Module to not run on ISE

---

ext/build_defaults.yaml

This commit updates the `repo_name` param to `puppet-enterprise-tools`. This is
a new repo that will contain non-Puppet-Platform tools (like PDK) for use by PE
customers. Even though we explicitly override this variable at ship time, this
is a good sane default.

(RE-12370) Update repo names

---

configs/platforms/osx-10.14-x86_64.rb
configs/projects/pdk.rb

This should be all that's needed in pdk-vanagon once the new versions of pdk-runtime are built (https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/job/platform_pdk-runtime_runtime-vanagon-packaging_master/85/)

(PDK-1378) Promote pdk-runtime to include change to use /etc/gitconfig

---

resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

This commit updates the error message displayed to users to be inline with
standard Puppet documentation practices.

(PDK-1168) Update error message for PDK under ISE

---

configs/components/pdk-create-ruby-tarballs.rb
configs/projects/pdk.rb
resources/files/install-tarballs/extract_all.rb

Previously the PDK build process created 50,000+ files which causes issues with
MSI installation and uninstallation times.  This commit is the start of a
process to decrease install time by generating less files.
This commit:
* Adds a new component called pdk-create-ruby-tarballs which is responsible for
taking a PDK installation files and compressing the ruby environments and
their respective gem and puppet gem caches.  Note that the ruby environment
which PDK runs in, at this time Ruby 2.4 is not compressed as it is required
for the decompression step.
* The new pdk-create-ruby-tarballs component will only run on Windows builds.
Later commits may remove this restriction.
* Adds a new file the to installation media called `extract_all.rb`. This small
script is responsible for extracting …

(PDK-1370) Create tarballs of ruby environment for Windows

---

resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb
resources/windows/wix/tarball.vbs

In commit d5db4214 the MSI build process was modified to create tarballs of the
various ruby environments, and lay down the extaction script.  This commit
modifies the MSI installation process to now call the extraction script.
* Add a VBScript Binary component. This is required so that we can pass error
messages back to the MSI Engine incase the extraction fails
* Adds a custom action to capture the INSTALLDIR as this property is not
available to Deferred Custom Actions
* Adds a Deferred Custom Action to extract the tarballs so that it can be run in
an elevated context

(PDK-1371) Extract tarballs during MSI Installation

---

configs/components/pdk-create-ruby-tarballs.rb
resources/files/install-tarballs/remove_all.rb
resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb
resources/windows/wix/tarball.vbs

Previously in commit 3bbaffb06 the MSI installation process extracted the
tarballs to their correct place on disk. However because the MSI engine did not
place those files, when uninstalling the MSI Engine leaves those files behind.
This commit modifies the MSI installation process to now call a removal script.
* Updates the tarball VBScript to be able to both extract and remove the tarball
contents
* Adds a custom action to capture the INSTALLDIR as this property is not
available to Deferred Custom Actions
* Adds a Deferred Custom Action to remove the extracted files so that it can be
run in an elevated context

(PDK-1373) Remove extracted files on MSI uninstall

---

configs/components/pdk-templates.rb
configs/components/puppet-forge-api.rb
configs/projects/pdk.rb

Updates byebug on Ruby > 2.1 to 11.0.1 for latest beaker.

(maint) Update byebug on Rubies > 2.1

---

configs/components/pdk-templates.rb
configs/components/puppet-forge-api.rb
configs/projects/pdk.rb

Installs them side by side to work around the nondeterministic behaviour of Bundler.

(maint) Install byebug 9.0.6 & 11.0.1

---

rakelib/check_download_links.rake

Fetches the list of platforms from the vanagon config (which is the
cause of the 2 Fedora related failures seen in the examples below, we no
longer build for those Fedora versions but they remain in our config).
The task then hits the pdk_download.cgi script and follows the redirects
until it gets to the actual package. If any of the package URLs do not
contain the specified version, the task will exit non-zero.
By default, the task will use the latest annotated tag name as the
version.
```
$ bundle exec rake check_download_links
Checking that PDK download links point to 1.11.1.0
debian-8-amd64 => Incorrect version! https://apt.puppet.com/pool/jessie/puppet/p/pdk/pdk_1.11.0.0-1jessie_amd64.deb
debian-9-amd64 => Incorrect version! …
```

(maint) Rake task to automate checking PDK download links

---

configs/components/puppet-forge-api.rb

https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-van-build_adhoc/BUILD_TARGET=windows-2012r2-x64,SLAVE_LABEL=beaker/52/

(maint) Install rb-readline into all ruby runtimes on Windows

---

configs/components/pdk-templates.rb

This will make it so the `chmod` invocation only prints changed modes on all platforms (currently it prints every file inspected on Linux which adds a lot of bloat to the build logs)
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-van-build_adhoc/53/

(FIXUP) Make chmod only output changes on all platforms

---

ext/build_defaults.yaml

Ugh. There's a set of circumstances where if PDK releases a new nightly
into 'puppet-nightly', it can create a directory in the place of a desired
symlink, causing puppet-agent problems later.
For now, be very specify about which repo nightly (aka nonfinal) builds
are delivered to.

(maint) Be specific about Puppet major version for nonfinal_repo_name

---

Gemfile

The latest version of the packaging gem pulls in a new dependency (csv) that is
incompatible with Ruby 2.2.5 which is used in the generic vanagon-promote job.

(maint) Pin packaging gem to 0.99.45

---

configs/components/rubygem-pdk.rb
resources/files/posix/pdk_env_wrapper
resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psd1
resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

Rather than hardcode the Ruby version in the wrapper script and
PowerShell module, this will populate that value during build time from
the pdk-runtime vanagon config.
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/62/

(PDK-1504,PDK-1524) Populate Ruby version in files during build

---

resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

Ansicon is not required on the newer Windows Terminal. This commit updates the
PDK Wrapper to detect the new Windows Terminal and not use ansicon.

(PDK-1521) Do not use ansicon under Windows Terminal

---

configs/components/puppet-runtime.json

We don't actually use this value, but it needs to be in place for the vanagon-component-promote script's validation logic.

(PDK-1548) Add a dummy location value to puppet-runtime.json

---

configs/components/puppet-forge-api.rb
configs/components/puppet-specifications.rb
configs/projects/pdk.rb

As of puppetlabs/puppet-forge-api#578, the task schema is no longer in
the puppet-forge-api repo.
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/71/

(maint) Fetch task schema from puppetlabs/puppet-specifications

---

Gemfile
configs/components/pdk-templates.rb
configs/platforms/fedora-31-x86_64.rb

Depends on https://github.com/puppetlabs/puppet-runtime/pull/248 (can drop e20d579 and bump runtime version once merged)
Successful build: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/72/

(PDK-1546) Add Fedora 31 to platform configs

---

resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

Previously the the PDK PowerShell module was susceptible to external environment
variable changes once the module was loaded.  For example run PDK, then Bolt and
then PDK again, it then fails with a Ruby error.  This was due to the module
setting Environment Variables only once during the module loading process.
This commit:
* Changes some of the variables to be module scoped ($Script) instead of
environment, as it's not needed.
* Modifies the SSL based env. vars prior to invoking PDK every time, instead of
only once.

(PDK-1547) Set SSL Env vars before running PDK in PowerShell Module

---

configs/components/pdk-templates.rb

Not sure why this wasn't added at the same time we added it for primary rubies, but it seems to be causing problems for the additional rubies now, probably related to the Rubygems/Bundler release.

(MAINT) Add `--skip-bundle-install` to additional rubies

---

configs/components/puppet-forge-api.rb

We'll have to come back and sort out how to get this working with rubygems > 3.0.0 later, but for now...
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/88/

(PDK-1590) Pin rubygems on ruby >= 2.4 to 3.0.0

---

configs/projects/pdk.rb

Successful ad-hoc build: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/111/

(MAINT) Bump nokogiri to >= 1.10.8 for CVE-2020-7595

---

resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

@jpogran Is there a quick way we could just have this script resolve the path dynamically? There should only ever be one 2.4.x version in that directory.

(MAINT) Bump Ruby version in PowerShell wrapper script

---

README.md

We should probably eventually deprecate the entire `Promoting and releasing new packages` section and point people towards a single source of truth on the process.
For now, I have updated the instructions in case someone does not go through the ticket template process to release a new build.

Update pkg release instructions

---

Gemfile
configs/components/pdk-templates.rb

Note that we still won't have the beaker deps pre-installed due to
issues with native extensions in beaker deps on Windows.

(MAINT) Re-enable bundle pre-install for Puppet 7.x

---

configs/components/pdk-templates.rb

This is the second part for https://github.com/puppetlabs/pdk/pull/935 making sure litmus is still installed with the pdk, but is not burdening down the alternative rubies.
This is not tested, as I currently have no VPN access. I hope I managed to find the right spot.

Only install system_tests gem on the main ruby

---

ext/build_defaults.yaml

The `gpg_key` setting is overridden by the one in `build-data`. Remove the
local soon-to-be-expired GPG key from the local repo for clarity and
cleanliness.

(RE-13454) Remove old gpg key from build_defaults.yaml

---

Gemfile
configs/components/gem-prune.rb
configs/components/pdk-templates.rb
configs/components/puppet-versions.rb
configs/components/rubygem-bundler.rb
configs/projects/pdk.rb
resources/puppet-versions/README

The `puppet-forge-api` component originally pulled in multiple files
from the Forge API codebase (which is a private repo) but at this point
it was only pulling in the PE version mapping file which is now
available from a public API endpoint that we can just pull from at build
time.
This PR refactors the component into a "file" based component that
queries the Rubygems API to gather a list of Puppet gem versions and
installs them into the appropriate gem caches.

(MAINT) Refactor `puppet-forge-api` component into `puppet-versions`

---

resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

This disables ansicon on Windows when running PDK in the intergrated terminal in VS Code. This prevents terminal wrapping issues and loss of terminal history due to ansicon attempting to control a modern conhost.
Fixes: https://github.com/puppetlabs/pdk/issues/829

(maint) Disable ansicon in VS Code

---

configs/platforms/el-6-x86_64.rb
configs/platforms/el-7-x86_64.rb

The CentOS mirrors for RHEL/Centos 6 have gone away and the mirrors for
7 will likely go away suddenly in the future as well. This change
switches the platform configs to use the actual RHEL images from
vmpooler instead of the Centos images we were using before.

(MAINT) Update RHEL platform configs to use RedHat pooler images

---

configs/components/pdk-templates.rb

On windows the ref was picking up the latest tag of pdk-vanagon, but looking for that same tag within the checkout of pdk-templates. As we tag vanagon with pre release tags for testing this broke our build.

(PDK-1107) Set templateref to main branch when building

---

Gemfile
configs/platforms/debian-11-amd64.rb
configs/platforms/fedora-32-x86_64.rb
configs/platforms/fedora-34-x86_64.rb
configs/platforms/osx-11-x86_64.rb
configs/platforms/windows-2019-x64.rb

Adds the following new build and test targets for the PDK build
pipelines:
- Debian 11
- Fedora 32
- Fedora 34
- OSX 11
Bumps the Windows build and test targets from 2012 R2 -> 2019.
Bumps vanagon to `~> 0.21.2` - this is the minimum version required
to obtain support for Debian 11.
------
**This PR is blocked from merging until:**

(puppetlabs/pdk#1093) Add new platform support for pdk; Bump vanagon ver

---

configs/components/rubygem-json_pure.rb
configs/projects/pdk.rb
resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

This PR requires: 
- https://github.com/puppetlabs/puppet-runtime/pull/478
- https://github.com/puppetlabs/pdk/pull/1130
Once these have been reviewed and merged the auto-promotion from those repos into pdk-vanagon will all this PR to remove the 2 commits tagged REMOVE
These PRs support the runtime and platform changes.

(puppetlabs/pdk#1126) Removal of Ruby 2.4. Default now 2.5

---

configs/platforms/fedora-30-x86_64.rb
configs/platforms/fedora-31-x86_64.rb
configs/platforms/osx-10.14-x86_64.rb

This removes the platform configs for fedora 30, fedora 31, and osx
10.14.

(maint) Remove platform definitions for EOL platforms

---

ext/build_defaults.yaml

This will skip Apple Notarization for pdk. Notarization fails due to
fsevents gem (which is built with an old SDK, causing notarization to fail).
If this issue is fixed, Apple notarization may be possible in the future.

(RE-13380) Set Apple notarization to false.

---

configs/platforms/windows-2019-x64.rb

choco update is removed in chocolatey 1.0, so we need to transition to
the proper command choco upgrade.

(maint) Use choco upgrade instead of deprecated choco update

---

configs/components/rubygem-json_pure_r27.rb

This PR bumps the ruby version used for this component to 2.7.6.
It would appear that a dependancy was bumped in [this commit](https://github.com/puppetlabs/puppet-runtime/compare/202204120...202204121). Since this happened, the pdk-vanagon builds have been failing.
I've tested a [build](https://jenkins-platform.delivery.puppetlabs.net/view/PDK/job/platform_pdk_pdk-van-init_main/126/) from the associated branch and it passed.
Hopefully this is the fix.

(MAINT) Bump json_pure_r27

---

Gemfile

This commit bumps the following gems:
* vanagon
* packaging
This is to ensure that we are inline with the latest versions available.

(MAINT) Bump build dependencies

---

configs/components/pdk-templates.json
configs/components/rubygem-pdk.json

To prepare for the next PDK patch release, this PR sets component versions back to 2.5.0

(CONT-413) Reset pdk rubygem version

---

configs/components/rubygem-json_pure_r27.rb

Ruby version 2.7.6 had a CVE reported last year. As a result references in the puppet-runtime project were bumped to 2.7.7.
For this compoent we hard code the additional_rubies hash key. Prior to this change it was set to 2.7.6 which was causing build failures.
This change updates the key to 2.7.7 so that the look up will work as expected.

(CONT-413) Bump additional ruby version

---

configs/platforms/ubuntu22.04-amd64.rb

Prior to this commit, Ubuntu 22.04 was not supported by pdk. This commit adds the Ubuntu 22.04 platform file.

(CONT-513) Add Ubuntu 22.04 platform file

---

configs/platforms/osx-10.15-x86_64.rb

OSX 10.15 support has been removed from pdk's ci-job-configs. This commit removes it from pdk-vanagon platforms for completeness.

(CONT-698) Remove OSX 10.15 support

---

resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

Prior to this change the PowerShell wrapper for PDK was pointing to Ruby 2.5.9.
This change updates the path to point to 2.7.7.

(CONT-728) Update PowerShell wrapper

---

configs/projects/pdk.rb

Prior to this commit, the package build was configured to generate build ids.
It turns out that this still causes conflicts with other packages.
This commit ensures that we are no longer generating build ids/

(CONT-760) Disable build ID generation

---

Gemfile

Prior to this commit the vanagon version has a dependency on a vulnerable version of git.
This commit bumps the version of vanagon which results in a newer version of git where the vulnerability is no longer present.

(maint) Bumping vanagon version

---

README.md

Prior to this commit, the Readme.md file in this repository barely had a short description and usage block with instructions.
This commit aims to enforce the standard Puppet documentation guidelines by formatting the document properly and to expand a bit the existing documentation with relevant information about the tool.

(CAT-1299) Expand documentation

---

configs/components/pdk-runtime.rb
configs/projects/pdk.rb

Previously, pdk required the pdk-runtime component to refer to a valid SHA in the https://github.com/puppetlabs/puppet-runtime repo which makes it difficult to test pdk-runtime changes before committing them.
This commit allows the pdk-runtime.json component to refer to an already built dev build that only exists locally such as:
{
"version":"202311141.4.g81059f6",
"location":"file:///home/josh/work/puppet-runtime/output"
}
Or a pdk-runtime build generated via Vanagon Generic Builder:
{
"version":"202308240.86.g81059f6",
"location":"https://builds.delivery.puppetlabs.net/puppet-runtime/81059f6336c6b8f5f77ab9a3700eb0b2b58d5bcc/artifacts/"
}
Where the pdk-runtime is relative to the 'location':
${location}/pdk-runtime-${version}.windows-2019-x64.tar.gz
Provide a detailed description of all …

Support building pdk using a dev puppet-runtime build

---

configs/platforms/fedora-36-x86_64.rb

We had previously used an altered setup, however the issue requiring that should have abated.

(CAT-1744) Set Fedora 36 image to use the default settings

---

configs/platforms/debian-9-amd64.rb
configs/platforms/el-6-x86_64.rb

Prior to this commit, we believed that support for Debian 9 and EL 6 was still active within the PDK. This is not the case, and as such, we are free to clean this code.

(CAT-1769) Cleanup legacy platforms

---

configs/platforms/osx-13-arm64.rb
configs/platforms/osx-13-x86_64.rb

Add support for Mac OSX 13 to the PDK.
Platform image for the arm64 version is being included but it may not be immediately added to the builds.

(CAT1788) Add Mac OSX 13 support

---

configs/platforms/el-8-aarch64.rb
configs/platforms/el-9-aarch64.rb
configs/platforms/osx-11-arm64.rb
configs/platforms/osx-12-arm64.rb
configs/platforms/ubuntu-18.04-aarch64.rb
configs/platforms/ubuntu-20.04-aarch64.rb

Adding additional build targets to expand Architecture support.

(CAT-1875) Add build targets for additional OS Architecture support

---

configs/platforms/fedora-40-x86_64.rb

Prior to this commit, Fedora 40 was not a supported platform in PDK. This commit adds the necessary infrastructure to start building Fedora 40 in Jenkins.

(CAT-1944) Fedora 40 support

---

configs/platforms/fedora-32-x86_64.rb
configs/platforms/fedora-34-x86_64.rb
configs/platforms/fedora-36-x86_64.rb

Prior to this commit, we decided to remove Fedora 36 from PDK support. This commit aims to reflect that decision. In addition, we are also cleaning up previous Fedora platforms that are no longer supported.

(CAT-1786) Remove Fedora <= 36 platforms

---

resources/windows/wix/tarball.vbs

This PR resolves the issue of a race condition were a user could force PDK's installer to perform arbitrary code. 
A hard coded location is added for the comSpec file and getTempName is now being used instead of reading from the TEMP environment variable
https://github.com/puppetlabs/bolt-vanagon/pull/199

(CAT-1421) - Dont use environment variables to determine executable locations in PDK MSI

---

configs/platforms/ubuntu-24.04-aarch64.rb

This PR is needed as the PDK pipeline is not detecting the latest PDK vanagon build version with the default for ubuntu-24.04-aarch64.
This should be updated to call to default when possible 

(CAT-2005) - Update ubuntu-24.04-aarch config to include default values

---

configs/projects/pdk.rb

Following a chat with @e-gris I have implemented suggested changes to add a package override to the pdk project that will disable __debug_package, as this was the main culprit causing build errors for el-8-aarch64.
I have also changed the formatting of the other package overrides for better readability.
After these changes I was able to successfully build a pdk package for el-8-aarch64 locally and in Jenkins.

(CAT-1989) As a PDK User I want AARCH Architecture to Redhat 8 to be available so that I can use them

---

Gemfile

Pin was coming through incorrectly and causing the build step to fail, pinning it in this way seems to work as is expected.

(BUGFIX) Change how packaging is pinned

---

configs/platforms/sles-12-x86_64.rb

Due to conflicts between a newer version of GIT required to resolve a lvl9 security vulnerability and SLES 12 it looks as if we will be unable to support it, as such given that General support for it has already ended we will be dropping it from the PDK

(CAT-2162) Remove support for SLES 12

---

configs/components/gem-prune.rb
configs/components/puppet-versions.rb

- Set ruby version for Puppet 8 from 3.2.0 to 3.1.0
- https://github.com/puppetlabs/pdk/pull/1443
- https://github.com/puppetlabs/puppet-runtime-private/pull/33

(CAT-2247) Remove support for Puppet 7 and Ruby 2.7
